### PR TITLE
Add CircleCI and improve coding style according to PEP8

### PR DESCRIPTION
**Pull request by zkan**
Changes proposed in this PR:
* Add `flake8` to check Python style.
* Improve the code according to [PEP8](https://www.python.org/dev/peps/pep-0008/)
* Add CircleCI configuration to run static analysis and unit tests.

Connected to #4.

### CODE REVIEW

**Comment by zkan** [comment]
I will fix the conflicts soon.

**Comment by zkan** [comment]
Just wonder how do you run the tests right now. Could you give me the command, please?

**Comment by pBouillon** [comment]
For tests, all you need to do is running each test file in test/ 
Then unittest module will display how many tests did succeed or didn't

**Comment by zkan** [comment]
I guess this https://github.com/pBouillon/Novigrad/pull/5 broke them. I'll try to fix.

**Pull request closed without merging**
