### PR TITLE
Modified package structure

### PR DESCRIPTION
**Pull request by vishnuramana**
Modified the package structure for easy access. Also removed the unused imports in the main scripts and test file.

### CODE REVIEW

**Comment by vishnuramana** [comment]
Modified the package structure. Also removed unused imports. Please let me know if the package is compiling and tests work. I was not able to run them locally.

**Comment by pBouillon** [comment]
@V1cHu Imports are following the [google styleguide](https://google.github.io/styleguide/pyguide.html#Imports)

**Comment by vishnuramana** [comment]
@pBouillon oh ok. I will revert that and make another commit.

**Comment by vishnuramana** [comment]
@pBouillon please check if the imports are right now :)

**Comment by pBouillon** [comment]
@V1cHu yep, alright !

**Comment by vishnuramana** [comment]
@pBouillon Thanks for the merge 👍

**Pull request merged**
